"""Added the super_name column

Revision ID: f20843924504
Revises: 08875d9c92cd
Create Date: 2025-04-02 11:33:37.468093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20843924504'
down_revision = '08875d9c92cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.drop_column('super_name')

    # ### end Alembic commands ###
